insert into ACCOUNT(CPF,EMAIL,NAME,PASSWORD) VALUES ('50727031846','VINI-GAVA@OUTLOOK.COM.BR','VINICIUS GAVA PEREIRA','a588039350fb48b8f0986ddb030ed0d28')

insert into CUSTOM_CHARACTER(CHARACTER_CLASS ,LEVEL ,NAME ,RACE,FK_C_ID  ) VALUES ('RANGER',1,'RODRIGO','HUMAN',1)
insert into CUSTOM_CHARACTER(CHARACTER_CLASS ,LEVEL ,NAME ,RACE,FK_C_ID ) VALUES ('WARRIOR',1,'MARCOS','HUMAN',1)